-- Binance-MS: OHLCV + funding_history (Plan C — legacy 프로젝트 대체)
-- Supabase Dashboard → SQL Editor 에 붙여넣기 (멱등)

CREATE TABLE IF NOT EXISTS public.ohlcv (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol          text NOT NULL,
    interval        text NOT NULL,
    ts              timestamptz NOT NULL,
    open            double precision NOT NULL,
    high            double precision NOT NULL,
    low             double precision NOT NULL,
    close           double precision NOT NULL,
    volume          double precision NOT NULL,
    taker_buy_base  double precision,
    CONSTRAINT ohlcv_symbol_interval_ts_key UNIQUE (symbol, interval, ts)
);

CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_interval_ts
    ON public.ohlcv (symbol, interval, ts DESC);
CREATE INDEX IF NOT EXISTS idx_ohlcv_ts ON public.ohlcv (ts DESC);

CREATE TABLE IF NOT EXISTS public.funding_history (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol        text NOT NULL,
    ts            timestamptz NOT NULL,
    funding_rate  double precision NOT NULL,
    CONSTRAINT funding_history_symbol_ts_key UNIQUE (symbol, ts)
);

CREATE INDEX IF NOT EXISTS idx_funding_history_symbol_ts
    ON public.funding_history (symbol, ts DESC);

-- backtest_runs 는 Phase 2-E 에 이미 존재. 없을 때만 생성.
CREATE TABLE IF NOT EXISTS public.backtest_runs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          text UNIQUE NOT NULL,
    started_at      timestamptz NOT NULL DEFAULT now(),
    completed_at    timestamptz,
    config_json     jsonb,
    summary_json    jsonb,
    verdict         text,
    operator_notes  text
);

ALTER TABLE public.ohlcv ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.funding_history ENABLE ROW LEVEL SECURITY;
-- service_role 은 RLS 우회. anon 차단용 빈 정책 없음 = MS Phase 2-E 와 동일(rls off 권장 시):
ALTER TABLE public.ohlcv DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.funding_history DISABLE ROW LEVEL SECURITY;
